### PR TITLE
"Download" button now generates a zip file

### PR DESCRIPTION
**Pull request by yabirgb**

### CODE REVIEW

**Comment by MahdiF** [comment]
Hey Thanks Yabir, I tried the new code and the generated zip file didn't have everything, it had the index.html & style.css with 0 bytes, and the js file had 1 line only. I tried it on Google Chrome.
I've attached the zip file so you can see by yourself.
Cheers,
[youtube-cover-video.zip](https://github.com/MahdiF/youtube-cover-video/files/75911/youtube-cover-video.zip)

**Comment by yabirgb** [comment]
It is because the script makes and ajax request to the file and the browsers don't like ajax calls from file:/// if you test it in a simple nodejs server or any webpage you can see it work. If you check the debug console in chrome you can see the error that I mention.

**Comment by yabirgb** [comment]
I have created a clone of your website so you can check it working without problem. http://yabirgb.github.io/youtube-cover-video/

**Comment by MahdiF** [comment]
Yeah I've already tested on my machine by creating a local server. Thanks
again, will merge your changes now :D

**Comment by yabirgb** [comment]
Ok and sorry for bothering you, I should have told you about but I forgot that.

**Comment by MahdiF** [comment]
not at all bro! It's my mistake, I'm still a beginner haha.

**Comment by MahdiF** [comment]
Yabir, check it now: http://mahdif.github.io/youtube-cover-video/

**Pull request merged**
